export const data = [
  {
    name: 'Sole - Dover, Whole, Fresh',
    description: 'ligula nec sem duis aliquam',
    price: 87.83,
    inStock: true,
    categoryId: 'Male',
    image_url: 'http://dummyimage.com/152x100.png/cc0000/ffffff',
  },
  {
    name: 'Water - Green Tea Refresher',
    description: 'semper rutrum nulla nunc purus phasellus in felis',
    price: 51.43,
    inStock: true,
    categoryId: 'Male',
    image_url: 'http://dummyimage.com/170x100.png/5fa2dd/ffffff',
  },
  {
    name: 'Table Cloth 54x54 White',
    description: 'neque aenean auctor gravida sem praesent id',
    price: 28.16,
    inStock: false,
    categoryId: 'Female',
    image_url: 'http://dummyimage.com/228x100.png/ff4444/ffffff',
  },
  {
    name: 'Flour - Bread',
    description: 'feugiat non pretium quis lectus suspendisse potenti',
    price: 20.35,
    inStock: true,
    categoryId: 'Female',
    image_url: 'http://dummyimage.com/115x100.png/5fa2dd/ffffff',
  },
  {
    name: 'Olives - Morracan Dired',
    description: 'non quam nec dui luctus rutrum nulla',
    price: 29.16,
    inStock: false,
    categoryId: 'Male',
    image_url: 'http://dummyimage.com/234x100.png/cc0000/ffffff',
  },
  {
    name: 'Tuna - Salad Premix',
    description: 'justo in blandit ultrices enim lorem ipsum dolor',
    price: 69.63,
    inStock: true,
    categoryId: 'Male',
    image_url: 'http://dummyimage.com/184x100.png/cc0000/ffffff',
  },
  {
    name: 'Squash - Sunburst',
    description:
      'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci',
    price: 30.65,
    inStock: false,
    categoryId: 'Female',
    image_url: 'http://dummyimage.com/204x100.png/cc0000/ffffff',
  },
  {
    name: 'Chicken - Thigh, Bone In',
    description: 'nam nulla integer pede justo lacinia eget tincidunt',
    price: 15.71,
    inStock: false,
    categoryId: 'Female',
    image_url: 'http://dummyimage.com/245x100.png/dddddd/000000',
  },
  {
    name: 'Doilies - 12, Paper',
    description: 'porttitor id consequat in consequat ut nulla',
    price: 64.82,
    inStock: false,
    categoryId: 'Male',
    image_url: 'http://dummyimage.com/141x100.png/ff4444/ffffff',
  },
  {
    name: 'Bread - Assorted Rolls',
    description: 'lacus purus aliquet at feugiat non pretium',
    price: 7.53,
    inStock: true,
    categoryId: 'Male',
    image_url: 'http://dummyimage.com/145x100.png/dddddd/000000',
  },
  {
    name: 'Flour - Bran, Red',
    description: 'ultrices vel augue vestibulum ante ipsum primis in',
    price: 88.65,
    inStock: true,
    categoryId: 'Male',
    image_url: 'http://dummyimage.com/194x100.png/dddddd/000000',
  },
  {
    name: 'Beer - Molson Excel',
    description: 'turpis integer aliquet massa id lobortis convallis',
    price: 6.88,
    inStock: true,
    categoryId: 'Male',
    image_url: 'http://dummyimage.com/246x100.png/5fa2dd/ffffff',
  },
  {
    name: 'Wine - Zonnebloem Pinotage',
    description: 'nunc proin at turpis a pede',
    price: 62.92,
    inStock: true,
    categoryId: 'Female',
    image_url: 'http://dummyimage.com/148x100.png/ff4444/ffffff',
  },
  {
    name: 'Juice - Clamato, 341 Ml',
    description: 'vel est donec odio justo sollicitudin ut',
    price: 9.53,
    inStock: false,
    categoryId: 'Female',
    image_url: 'http://dummyimage.com/226x100.png/ff4444/ffffff',
  },
  {
    name: 'Parsley - Fresh',
    description:
      'magna bibendum imperdiet nullam orci pede venenatis non sodales sed',
    price: 25.41,
    inStock: false,
    categoryId: 'Male',
    image_url: 'http://dummyimage.com/140x100.png/5fa2dd/ffffff',
  },
  {
    name: 'Pork - Tenderloin, Fresh',
    description:
      'phasellus id sapien in sapien iaculis congue vivamus metus arcu',
    price: 66.26,
    inStock: false,
    categoryId: 'Female',
    image_url: 'http://dummyimage.com/241x100.png/5fa2dd/ffffff',
  },
  {
    name: 'Cinnamon Buns Sticky',
    description: 'lectus in est risus auctor sed tristique',
    price: 73.36,
    inStock: false,
    categoryId: 'Female',
    image_url: 'http://dummyimage.com/138x100.png/5fa2dd/ffffff',
  },
  {
    name: 'Mix Pina Colada',
    description: 'ullamcorper purus sit amet nulla quisque arcu',
    price: 44.96,
    inStock: false,
    categoryId: 'Female',
    image_url: 'http://dummyimage.com/143x100.png/cc0000/ffffff',
  },
  {
    name: 'Gooseberry',
    description: 'tellus in sagittis dui vel nisl duis ac nibh',
    price: 58.38,
    inStock: true,
    categoryId: 'Male',
    image_url: 'http://dummyimage.com/112x100.png/dddddd/000000',
  },
  {
    name: 'Chinese Foods - Pepper Beef',
    description: 'in faucibus orci luctus et ultrices posuere cubilia',
    price: 93.34,
    inStock: true,
    categoryId: 'Female',
    image_url: 'http://dummyimage.com/136x100.png/5fa2dd/ffffff',
  },
];
